name: Create commit on a new issue
on:
  issues:
    types: [opened]

jobs:
 commit-with-actions:
   runs-on: ubuntu-latest
   steps:
    - name: "dump github context"
      run: echo "${{ tojson(github)}}" | jq
      shell: bash  