name: Create a commit on new issue
on:
  issues:
    types: [opened]

jobs:
  commet-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github contest"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
  
